server:
  port: 8761

##
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
  file: /data/logs/${spring.application.name}.log

eureka:
  instance:
    #hostname: 119.23.127.205
    hostname: 127.0.0.1
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false   #false表示不向注册中心注册自己
    fetchRegistry: false        #false表示自己就是注册中心，职责是维护实例，不参加检索
    serviceUrl:                 #设置eureka server的交互地址，即对外暴露的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: wjsy-register-eureka
